### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by shellscape** [mszoek/airyx#72]
We'd like to see some.

**Comment by mszoek** [comment]
It doesn't look like much yet :) Most of my work so far is on "plumbing" - toolchain, Cocoa APIs, system services. The desktop right now is KWin + elementaryOS icons + helloSystem Filer & Menu + some other bits in various states of completion as I work towards the 0.3.0 build. 

I'll see what I can do.

**Comment by augustohp** [comment]
There are [screenshots][] in a [comment on Hacker News][1].

[1]: https://news.ycombinator.com/item?id=28070125
[screenshots]: https://imgur.com/a/OsxT3GI

**Comment by mszoek** [comment]
Interesting. Those are mainly the helloSystem desktop and applications - which is fair because Airyx 0.2.x didn't have much of a GUI of its own. (It still doesn't - the desktop is still based on hello's components although they are evolving under the hood.) I'll try to make a few that demo the unique things about Airyx and some of the 0.3.0 features that I'm working on.

**Comment by mszoek** [comment]
I added a few pre-release 0.3.0 images at Airyx.org to give a sense of the future direction.
